/**
 * SensataPte7300 — Hardware bringup test
 *
 * Run ON REAL HARDWARE only. Not part of the SIL / CMake build.
 *
 * Usage:
 *   Call run_pte7300_hardware_test() from a FreeRTOS task or main loop
 *   after MX_I2C4_Init() has completed.
 *
 * Debug workflow:
 *   1. Check that probe_mux() returns Ok before anything else.
 *   2. Check that probe_sensor() returns Ok (sensor ACKs on I2C).
 *   3. Attach a logic analyzer and compare logged bytes against the
 *      ASSUMED protocol in SensataPte7300.hpp.
 *   4. If read_measurement_raw() returns CrcError, set use_crc=false
 *      and log raw bytes to identify the real frame layout.
 *   5. If it returns I2cError, the trigger byte (0xAC) may be wrong —
 *      try reading directly without a trigger write.
 */

#include "../SensataPte7300.hpp"
#include "../SensataPte7300HardwareTest.hpp"
#include <cstdio>

using namespace sensata;
using namespace sensata::mux;

// ---------------------------------------------------------------------------
// Test configuration — adapt to your board wiring
// ---------------------------------------------------------------------------

static constexpr uint8_t  k_test_mux_address     = 0x70; // A2=A1=A0=0
static constexpr uint8_t  k_test_sensor_channel  = 0;    // PTE7300 on channel 0
static constexpr uint8_t  k_test_sensor_address  = 0x6D; // 7-bit, excluding CRC

// Set to false to skip CRC and log raw bytes for protocol analysis.
static constexpr bool     k_test_use_crc         = false;

// 100 bar for a tank sensor, 400 bar for a COPV sensor (per DPRComputer
// reference project) -- set to match whichever physical part is under test.
static constexpr float    k_test_pressure_full_scale_bar = 100.0f;

#define LOG(fmt, ...) printf("[PTE7300] " fmt "\r\n", ##__VA_ARGS__)

// ---------------------------------------------------------------------------
// I2C handle from Core/Src/main.c (generated by STM32CubeMX)
// ---------------------------------------------------------------------------

extern "C" I2C_HandleTypeDef hi2c1;

static Pca9547Mux testMux(&hi2c1, k_test_mux_address, 100);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static const char* status_str(Status s)
{
    switch (s) {
        case Status::Ok:                return "Ok";
        case Status::I2cError:          return "I2cError";
        case Status::InvalidChannel:    return "InvalidChannel";
        case Status::MuxNotFound:       return "MuxNotFound";
        case Status::MuxChannelMismatch:return "MuxChannelMismatch";
        case Status::SensorNotFound:    return "SensorNotFound";
        case Status::CrcError:          return "CrcError";
        case Status::InvalidFrame:      return "InvalidFrame";
        case Status::Timeout:           return "Timeout";
        case Status::ProtocolNotDefined:return "ProtocolNotDefined";
        default:                        return "Unknown";
    }
}

static const char* step_str(Pte7300Step step)
{
    switch (step) {
        case Pte7300Step::None:        return "None";
        case Pte7300Step::MuxSelect:   return "MuxSelect";
        case Pte7300Step::WriteStart:  return "WriteStart";
        case Pte7300Step::ReadDspT:    return "ReadDspT";
        case Pte7300Step::ReadDspS:    return "ReadDspS";
        case Pte7300Step::ReadStatus:  return "ReadStatus";
        case Pte7300Step::ReadSerial:  return "ReadSerial";
        default:                       return "Unknown";
    }
}

static void log_mux_register(SensataPte7300& drv)
{
    auto r = drv.read_mux_control_register();
    if (r.status != Status::Ok) {
        LOG("  mux reg read FAILED (%s)", status_str(r.status));
        return;
    }
    bool    en  = (r.value & 0x08) != 0;
    uint8_t ch  = r.value & 0x07;
    LOG("  mux ctrl reg = 0x%02X  (enabled=%d  channel=%d)", r.value, en ? 1 : 0, ch);
}

// ---------------------------------------------------------------------------
// Hardware test entry point
// ---------------------------------------------------------------------------

void run_pte7300_hardware_test()
{
    SensorConfig cfg;
    cfg.mux_address_7bit    = k_test_mux_address;
    cfg.mux_channel         = k_test_sensor_channel;
    cfg.sensor_address_7bit = k_test_sensor_address;
    cfg.i2c_timeout_ms      = 10;
    cfg.use_crc             = k_test_use_crc;
    cfg.pressure_full_scale_bar = k_test_pressure_full_scale_bar;

    SensataPte7300 drv(&testMux, &hi2c1, cfg);

    LOG("=== PTE7300 hardware test START ===");
    LOG("    MUX  addr=0x%02X  channel=%d", k_test_mux_address, k_test_sensor_channel);
    LOG("    PTE  addr=0x%02X  use_crc=%d", k_test_sensor_address, k_test_use_crc ? 1 : 0);

    // ------------------------------------------------------------------
    // 1 — Probe PCA9547
    // ------------------------------------------------------------------
    LOG("[1] Probing PCA9547 at 0x%02X ...", k_test_mux_address);
    Status s = drv.probe_mux();
    if (s != Status::Ok) {
        LOG("  FAIL (%s) — check VDD, pull-ups, address pins A2/A1/A0", status_str(s));
        return;
    }
    LOG("  OK");
    log_mux_register(drv);

    // ------------------------------------------------------------------
    // 2 — Walk all 8 channels, verify control register each time
    // ------------------------------------------------------------------
    LOG("[2] Walking channels 0..7 ...");
    for (uint8_t ch = 0; ch <= 0; ++ch) {
        s = drv.select_channel(ch);
        if (s != Status::Ok) {
            LOG("  ch%d  select FAILED (%s)", ch, status_str(s));
            continue;
        }
        auto r = drv.read_mux_control_register();
        uint8_t expected = static_cast<uint8_t>(0x08 | ch);
        if (r.status != Status::Ok) {
            LOG("  ch%d  read FAILED (%s)", ch, status_str(r.status));
        } else if (r.value != expected) {
            LOG("  ch%d  MISMATCH got=0x%02X expected=0x%02X", ch, r.value, expected);
        } else {
            LOG("  ch%d  OK (ctrl=0x%02X)", ch, r.value);
        }
    }

    // ------------------------------------------------------------------
    // 3 — Select PTE7300 channel
    // ------------------------------------------------------------------
    LOG("[3] Selecting sensor channel %d ...", k_test_sensor_channel);
    s = drv.select_channel(k_test_sensor_channel);
    if (s != Status::Ok) {
        LOG("  FAIL (%s)", status_str(s));
        return;
    }
    LOG("  OK");
    log_mux_register(drv);

    // ------------------------------------------------------------------
    // 4 — Probe PTE7300
    // ------------------------------------------------------------------
    LOG("[4] Probing PTE7300 at 0x%02X ...", k_test_sensor_address);
    s = drv.probe_sensor();
    if (s != Status::Ok) {
        LOG("  FAIL (%s)", status_str(s));
        LOG("  Hints:");
        LOG("    - Verify sensor is powered (3.3–5.5 V)");
        LOG("    - Pin 5 on PTE7300 is labelled 'SDC' — confirm it is SCL on your schematic");
        LOG("    - Try address 0x6D if 0x6C does not respond");
        LOG("    - 0xDA ('with CRC') is NOT a valid 7-bit HAL address — do not use it directly");
    } else {
        LOG("  OK — PTE7300 ACKs on the bus");
    }

    // ------------------------------------------------------------------
    // 5 — Read measurement
    // ------------------------------------------------------------------
    LOG("[5] read_measurement_raw ...");
    auto meas = drv.read_measurement_raw();
    LOG("  status = %s  (failed at step: %s)", status_str(meas.status), step_str(drv.last_step()));

    if (meas.status == Status::Ok) {
        LOG("  pressure               = %.3f bar (%.2f psi)  (raw=%d, 0x%04X)",
            static_cast<double>(meas.value.pressure.pressure_bar),
            static_cast<double>(meas.value.pressure.pressure_psi),
            static_cast<int>(meas.value.pressure.pressure_raw),
            static_cast<uint16_t>(meas.value.pressure.pressure_raw));
        LOG("  bridge_temperature_raw = %d (0x%04X)",
            static_cast<int>(meas.value.temperature.bridge_temperature_raw),
            static_cast<uint16_t>(meas.value.temperature.bridge_temperature_raw));
        LOG("  status_raw             = %d (0x%04X)",
            static_cast<int>(meas.value.status.status_raw),
            static_cast<uint16_t>(meas.value.status.status_raw));
        LOG("  temperature            = %.2f C", static_cast<double>(meas.value.temperature.temperature_c));

    } else if (meas.status == Status::CrcError) {
        LOG("  CRC failed — retry with k_test_use_crc=false to see raw bytes");
        LOG("  Then compare with logic analyzer to find real CRC params");

    } else if (meas.status == Status::I2cError) {
        LOG("  I2cError on measurement read");
        LOG("  Register protocol (CMD/DSP_T/DSP_S/STATUS) is confirmed from");
        LOG("  a working reference driver -- check wiring/address, not the protocol");

    } else if (meas.status == Status::Timeout) {
        LOG("  Timeout — increase i2c_timeout_ms or check clock stretching");
    }

    // ------------------------------------------------------------------
    // 6 — Read serial number
    // ------------------------------------------------------------------
    LOG("[6] read_device_serial ...");
    auto serial = drv.read_device_serial();
    LOG("  status = %s", status_str(serial.status));
    if (serial.status == Status::Ok) {
        LOG("  serial = 0x%08lX (%lu)",
            static_cast<unsigned long>(serial.value),
            static_cast<unsigned long>(serial.value));
    }

    LOG("=== PTE7300 hardware test END ===");
}

// ---------------------------------------------------------------------------
// Lean data-only read: just pressure (bar) and temperature (C), no mux
// probing / channel walk / serial number / hints. Call every loop
// iteration from main() -- unlike run_pte7300_hardware_test(), this does
// not block or loop internally.
// ---------------------------------------------------------------------------

void pte7300_print_data()
{
    SensorConfig cfg;
    cfg.mux_address_7bit        = k_test_mux_address;
    cfg.mux_channel              = k_test_sensor_channel;
    cfg.sensor_address_7bit      = k_test_sensor_address;
    cfg.i2c_timeout_ms           = 10;
    cfg.use_crc                  = k_test_use_crc;
    cfg.pressure_full_scale_bar  = k_test_pressure_full_scale_bar;

    SensataPte7300 drv(&testMux, &hi2c1, cfg);

    auto meas = drv.read_measurement_raw();
    if (meas.status == Status::Ok) {
        LOG("pressure=%.3f bar (%.2f psi)  temperature=%.2f C",
            static_cast<double>(meas.value.pressure.pressure_bar),
            static_cast<double>(meas.value.pressure.pressure_psi),
            static_cast<double>(meas.value.temperature.temperature_c));
    } else {
        LOG("read failed: %s (step=%s)", status_str(meas.status), step_str(drv.last_step()));
    }
}

// ---------------------------------------------------------------------------
// I2C bus scanner — probes every address on every mux channel, forever.
// ---------------------------------------------------------------------------

static constexpr uint32_t k_scan_i2c_timeout_ms = 5;
static constexpr uint32_t k_scan_loop_delay_ms  = 500;
// probe_sensor() uses 3 trials; a single-trial probe can miss a device on a
// channel with slower bus rise time (weaker/missing local pull-ups, more
// connector capacitance), so match that here to rule out false negatives.
static constexpr uint32_t k_scan_trials         = 3;

// Standard 7-bit scan range: 0x00-0x07 and 0x78-0x7F are reserved addresses.
static constexpr uint8_t k_scan_addr_min = 0x03;
static constexpr uint8_t k_scan_addr_max = 0x77;

void run_pte7300_i2c_scanner()
{
    Pca9547Mux mux(&hi2c1, k_test_mux_address, k_scan_i2c_timeout_ms);

    LOG("=== PTE7300 I2C bus scanner START ===");
    LOG("    MUX addr=0x%02X  channels 0..%d  addr range 0x%02X-0x%02X  loop delay=%lu ms",
        k_test_mux_address, k_pca9547_max_channel,
        k_scan_addr_min, k_scan_addr_max,
        static_cast<unsigned long>(k_scan_loop_delay_ms));

    while (true) {
        for (uint8_t ch = 0; ch <= 0; ++ch) {
            Status s = mux.select_channel(ch);
            if (s != Status::Ok) {
                LOG("  ch%d  mux select FAILED (%s)", ch, status_str(s));
                continue;
            }

            uint8_t found_count = 0;
            for (uint8_t addr = k_scan_addr_min; addr <= k_scan_addr_max; ++addr) {
                HAL_StatusTypeDef hs = HAL_I2C_IsDeviceReady(
                    &hi2c1, static_cast<uint16_t>(addr) << 1, k_scan_trials, k_scan_i2c_timeout_ms);
                if (hs == HAL_OK) {
                    LOG("  ch%d  found device at 0x%02X", ch, addr);
                    found_count++;
                }
            }
            if (found_count == 0) {
                LOG("  ch%d  no devices found", ch);
            }
        }

        LOG("--- scan cycle complete, waiting %lu ms ---",
            static_cast<unsigned long>(k_scan_loop_delay_ms));
        HAL_Delay(k_scan_loop_delay_ms);
    }
}

// ---------------------------------------------------------------------------
// Channel-0 scope probe — bursts of raw I2C writes on mux channel 0, so
// signal integrity after the mux can be inspected with an oscilloscope.
// See header doc-comment for what to look for on the scope.
// ---------------------------------------------------------------------------

static constexpr uint32_t k_probe_burst_ms   = 500;
static constexpr uint32_t k_probe_idle_ms    = 500;
static constexpr uint32_t k_probe_i2c_timeout_ms = 5;

void run_pte7300_channel0_scope_probe()
{
    Pca9547Mux mux(&hi2c1, k_test_mux_address, k_probe_i2c_timeout_ms);

    LOG("=== channel-0 scope probe START ===");
    LOG("    selecting mux channel 0, then bursting writes to 0x%02X", k_test_sensor_address);
    LOG("    burst=%lu ms  idle=%lu ms  (attach scope to SD0/SC0, downstream of the mux)",
        static_cast<unsigned long>(k_probe_burst_ms),
        static_cast<unsigned long>(k_probe_idle_ms));

    const uint16_t addr = static_cast<uint16_t>(k_test_sensor_address) << 1;
    // Any register address works to generate bus traffic for the scope --
    // use the pressure ("DSP_S") register.
    uint8_t        byte = k_pte7300_reg_dsp_s;

    while (true) {
        // Re-verify (not just re-select) the channel at the start of every
        // burst: if the mux ever silently drops back to disabled (e.g. a
        // reset-pin glitch), this catches it instead of hammering the
        // sensor address into a floating/disconnected bus without saying so.
        Status s = mux.select_channel_verified(0);
        if (s != Status::Ok) {
            LOG("  mux channel-0 select/verify FAILED (%s) — retrying in %lu ms",
                status_str(s), static_cast<unsigned long>(k_probe_idle_ms));
            HAL_Delay(k_probe_idle_ms);
            continue;
        }

        uint32_t txn_count = 0;
        uint32_t ack_count = 0;
        uint32_t t_start   = HAL_GetTick();

        while ((HAL_GetTick() - t_start) < k_probe_burst_ms) {
            HAL_StatusTypeDef hs = HAL_I2C_Master_Transmit(
                &hi2c1, addr, &byte, 1, k_probe_i2c_timeout_ms);
            txn_count++;
            if (hs == HAL_OK) ack_count++;
        }

        LOG("  ch0 verified  burst: %lu txns, %lu ACKed",
            static_cast<unsigned long>(txn_count),
            static_cast<unsigned long>(ack_count));

        HAL_Delay(k_probe_idle_ms);
    }
}
